(WIP) feat: ⚡️ Add `serverURL` & `serverPort` options (for Hugo Server)
NiklasRosenstein/pydoc-markdown pull request #202
Opened 2021-08-15 13:17 UTC by melMass

Hi,

I wanted a way to use a LAN server instead of localhost, but it does not seem easily doable with configurations only.
I did not find lots of info on the matter on Hugo's forums but it seems others are having the same issue.

This PR almost works, by settings `serverURL` to 0.0.0.0 (outside localhost) & `serverPort` to `8080` (an open port on my router) I can access the doc from anywhere on the local network. 

The only issue is that all the links are pointing to `localhost`... But replacing localhost with the machine's IP does work. I tried to set the IP as `baseURL` as advised in a Hugo issue but that did not work with pydoc markdown.

Tell me if there is an interest in making it part of the library.

2021-08-16 20:39 UTC, NiklasRosenstein requested changes
* Two small nits
* Could you please add an entry to the [`.changelog/_unreleased.yml`](https://github.com/NiklasRosenstein/pydoc-markdown/blob/develop/.changelog/_unreleased.yml) file? Add your GitHub username at the end of the description as in `... (@melMass)` :)

2021-08-16 20:39 UTC, NiklasRosenstein commented on pydoc-markdown/src/pydoc_markdown/contrib/renderers/hugo.py
> +    return urljoin(f"http://{self.config.serverURL}:{self.config.serverPort}/", urlinfo.path)
nit: Use `'` (single quote) to be consistent with the rest of the code

2021-08-16 20:39 UTC, NiklasRosenstein commented on pydoc-markdown/src/pydoc_markdown/contrib/renderers/hugo.py
> +  serverURL: t.Optional[str] = "127.0.0.1"
nit: Use `'` (single quote) to be consistent with the rest of the code

2021-08-16 20:42 UTC, NiklasRosenstein commented
> I tried to set the IP as baseURL as advised in a Hugo issue but that did not work with pydoc markdown.

Hm this is weird, I would definitely expect that to work. 🤔 Do the URLs in the generated HTML not respect the baseURL at all?

2021-08-16 22:54 UTC, NiklasRosenstein commented
Btw. I just merged #204 so you will need to merge and reapply, sorry about that 😄

2021-08-16 23:48 UTC, melMass commented
> Btw. I just merged #204 so you will need to merge and resolve conflicts, sorry about that 😄

No problem, I'm checking the image parsing first and I'll go back to this one. I need to test this in Hugo only first to understand how it's handled there.

> Do the URLs in the generated HTML not respect the baseURL at all?

I will check this as well as I might have omitted the `http://` part (not sure yet):
I think this was my config
```yaml
baseURL: "0.0.0.0"
serverURL: "0.0.0.0"
```

I'm checking the other issue using a `Processor` and your notes now

2021-08-17 14:35 UTC, melMass commented
I'm asking here because I have yet to create the dedicated PR, but what steps should be taken to add a processor?

For now I called the processor `images` defined in `pydoc_markdown.contrib.processors.images:ImagesProcessor`.

I added it to both the `setup.py`'s `pydoc_markdown.interfaces.Processor` and the `PydocMarkdown.processors`'s default_factory.

For now, I just print in all interfaces to understand the flow of it all, but when I add it to my config I have the `ModuleNotFoundError: No module named 'images'`

2021-08-17 15:42 UTC, NiklasRosenstein commented
Hey @melMass , [Discussion](https://github.com/NiklasRosenstein/pydoc-markdown/discussions) would be the right place for this kind of question.😃 Would you mind opening a topic and we can discuss the image processor topic there?

2021-08-17 16:18 UTC, melMass commented
> Hey @melMass , [Discussion](https://github.com/NiklasRosenstein/pydoc-markdown/discussions) would be the right place for this kind of question.😃 Would you mind opening a topic and we can discuss the image processor topic there?

Definitely, I forgot about discussions!

2021-12-06 10:46 UTC, Heiss commented
Hey,

i want this feature, because i work in WSL2 and the default values are not usable in my setup. So it would be super handy to define the baseurl and port.
What needs to be done to get an approval? How can i help you?

I would need this feature asap, because my current workaround is ugly: clone the fork of @melMass into my venv and copy my gitlab PR into it. :) This is not a good solution to publish, because pydoc-markdown changes the dir structure.

Thank you.

2021-12-12 11:08 UTC, NiklasRosenstein commented
Hi @Heiss ,

I've opened a new PR https://github.com/NiklasRosenstein/pydoc-markdown/pull/231 for @melMass 's changes because I don't have permission to push to their fork; to address the nits. :)

I'll look to merge it and publish a new version soon.

Closing this in favor of #231.

2021-12-12 11:08 UTC, closed without merging