Add option to Render the heading#1 for letting readthedocs to generate TOC automatically #214
NiklasRosenstein/pydoc-markdown pull request #216
Opened 2021-10-03 07:32 UTC by t6847kimo

Hi, sorry for late response.
Please take a look at it, thanks!

2021-10-03 15:28 UTC, NiklasRosenstein requested changes
Hey @t6847kimo , thanks for the PR. I have to think about this a bit more. The `Renderer.render()` method does not accept a `page_title` argument and I'm unsure if I want to add it to the interface.

2021-10-03 15:28 UTC, NiklasRosenstein commented on src/pydoc_markdown/contrib/renderers/markdown.py
> +  def render_to_stream(self, modules: t.List[docspec.Module], stream: t.TextIO, page_title:str="API documentation"):
```suggestion
  def render_to_stream(self, modules: t.List[docspec.Module], stream: t.TextIO, page_title: str = "API documentation"):
```

nit

2021-10-03 15:28 UTC, NiklasRosenstein commented on src/pydoc_markdown/contrib/renderers/markdown.py
> +  def render(self, modules: t.List[docspec.Module], page_title:str) -> None:
```suggestion
  def render(self, modules: t.List[docspec.Module], page_title: str) -> None:
```
nit

2021-10-03 15:57 UTC, NiklasRosenstein commented
I just noticed that I even [suggested this](https://github.com/NiklasRosenstein/pydoc-markdown/issues/214#issuecomment-912430831) 🥲 

> There's many was this could be done. I think I would prefer an option in the Mkdocs renderer like render_page_title and that option is either passed to Page.render() or is set as an option in the Markdown renderer along with the title string.

2021-10-12 15:56 UTC, t6847kimo commented
Hi, may I know the current status?
Can I help anything?

2021-12-12 12:26 UTC, NiklasRosenstein commented
Hey @t6847kimo , sorry for the long silence. I've made a few changes before merging, that's why I create a new PR for it. Thanks for the contribution!

2021-12-12 12:26 UTC, closed without merging